apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e4ud0b7pt-go
  janus-idp.io/tekton: e4ud0b7pt-go
  backstage.io/kubernetes-id: e4ud0b7pt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e4ud0b7pt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
